# Meetapp
version: '3.6'

services:
  database:
    image: postgres:11.5-alpine
    volumes:
      - postgres-data:/var/lib/posgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

  redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  api:
    build: .
    volumes:
      - .:/www/app
    ports:
      - '3333:3333'
    command: 'yarn dev'
    links:
      - database
      - redis

  queue:
    build: .
    volumes:
      - .:/www/app
    command: 'yarn queue'
    links:
      - database
      - redis

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
